apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          name: ""
          resources:
            requests:
              cpu: 10m
              memory: 1Gi
          workingDir: /workspace/source
        steps:
        - image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.27.0
          name: git-clone
          workingDir: /workspace
          resources: {}
          script: |
            #!/bin/sh
            export SUBDIR="source"
            echo "git cloning url: $REPO_URL version $PULL_BASE_REF@$PULL_BASE_SHA to dir: $SUBDIR"
            git config --global --add user.name raghul@tobyre.com
            git config --global --add user.email toby-bot-user
            git config --global credential.helper store
            git clone $REPO_URL $SUBDIR
            cd $SUBDIR
            git checkout staging
            git status

        - image: ghcr.io/jenkins-x/jx-release-version:2.5.0
          name: next-version
          resources: {}
          script: |
            #!/usr/bin/env sh
            jx-release-version -next-version auto > VERSION
            
        - image: ghcr.io/jenkins-x/jx-boot:3.2.206
          name: jx-variables
          resources: {}
          script: |
            #!/usr/bin/env sh
            jx gitops variables 
        - name: replace-in-yaml
          image: docker.io/mikefarah/yq:4@sha256:34f1d11ad51dc4639fc6d8dd5ade019fe57cf6084bb6a99a2f11ea522906033b #tag: 4, amd
          script: |
            #!/bin/sh
            source .jx/variables.sh
            /usr/bin/yq e  ".image.tag= \"$VERSION\""  -i   charts/api/values-staging.yaml
            /usr/bin/yq e  ".image.tag= \"$VERSION\""  -i   charts/api/values-prod.yaml
        - image: ghcr.io/jenkins-x/jx-changelog:0.0.47
          name: promote-changelog
          resources: {}
          script: |
            #!/usr/bin/env sh
            source .jx/variables.sh
            echo "$VERSION" > VERSION
            cat VERSION
            # jx gitops yset -p version -v "$VERSION" -f ./charts/$REPO_NAME/Chart.yaml
            jx gitops yset -p appVersion -v "$VERSION" -f ./charts/$REPO_NAME/Chart.yaml
            jx gitops yset -p 'image.repository' -v $DOCKER_REGISTRY/$APP_NAME -f ./charts/$REPO_NAME/values.yaml
            jx gitops yset -p 'image.tag' -v "$VERSION" -f ./charts/$REPO_NAME/values.yaml;
            git config --global --add user.name toby-bot-user
            git config --global --add user.email raghul@tobyre.com
            git add .
            git commit -m "chore: release $VERSION" 
            #git push --force origin staging
            jx create pullrequest -t "Promote to Master" --base master
            exit 0
        - image: ghcr.io/jenkins-x/jx-boot:3.2.206
          name: jx-variable
          resources: {}
          script: |
            #!/usr/bin/env sh
            jx gitops variables 
        - image: gcr.io/kaniko-project/executor:v1.6.0-debug
          name: build-container-build
          resources: {}
          script: |
            #!/busybox/sh
            source .jx/variables.sh
            cp /tekton/creds-secrets/tekton-container-registry-auth/.dockerconfigjson /kaniko/.docker/config.json
            /kaniko/executor $KANIKO_FLAGS --context=/workspace/source --dockerfile=${DOCKERFILE_PATH:-Dockerfile} --destination=$PUSH_CONTAINER_REGISTRY/$APP_NAME:$VERSION          
  podTemplate: {}

  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
